### PR TITLE
Add metadata automatically, and push it all to the website

### PR DESCRIPTION
**Pull request by bsilver8192**
This should be the last piece of adding metadata to books which lack it,
and then pushing the result to the website (including covers).

https://github.com/GITenberg/The-Other-Now_51112 is a repository I
tested this on, and it seems to work nicely.

### CODE REVIEW

**Comment by bsilver8192** [comment]
@eshellman : If you agree this looks reasonable, then we're ready to deploy this and run it over all the books. What do you think?

**Comment by eshellman** [comment]
I would do two things
1. deploy the update server
2. test it on four types of repos
 - a repo that's recently been updated: 36779
 - a repo added in the second wave (2016) but not updated: 48100
 - a repo added in the first wave (2014) but not updated: 28100
 - a repo newly added with gitberg (also tests that we've not broken gitberg)

**Comment by bsilver8192** [comment]
Ok, I did that and it mostly worked. Had a few issues to resolve with the actual deploy image not quite working as intended, and non-ASCII YAML in one of those repos. The version now deployed seems to be fully functional, except without gitenberg-dev/giten_site#76 48100 doesn't make it all the way to the website. You can see what the autoupdater did in the three repos you mentioned and 51120.

I think I've got something working to add repos to the SQS queue from the command line too (which is how I tested), but I'm going to hold off on sending it out until it's fully tested, which is waiting on you to deploy gitenberg-dev/giten_site#76 and confirm you don't see anything silly in how it handled those test repos.

**Comment by bsilver8192** [comment]
Ran it over all the repositories, and it looks good (with one more tweak to work better when building ebooks takes time). Everything looks like it has covers now! Autoscaling up and down worked nicely too, so it took about 24 hours total to get through everything with 10 t2.micro instances.

A total of 3 repositories failed 5 times, so they got dropped into the dead letter queue as intended (the rest worked). GITenberg/Night-of-the-Living-Dead_23053 has no commits, so it's unsurprising it failed. GITenberg/_50624 and GITenberg/_50625 look weird from the names, and their metadata is missing titles+authors+etc.

**Comment by eshellman** [comment]
I'll follow up with the 3 problem repos. But this is great news!

**Pull request merged**
